import type { LibraryExercise } from './types';

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // CHEST + TRICEPS
  {
    id: 'bench-press',
    name: 'Bench Press',
    muscle: 'Chest',
    secondary: 'Triceps',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Flat Barbell', 'Incline Barbell', 'Decline Barbell', 'Smith Machine Flat', 'Dumbbell Flat'],
    tips: ['Retract scapula before unracking', 'Lower bar to mid-chest with control', 'Drive feet into floor for stability'],
    splitIds: ['ct', 'ctbb'],
    category: ['Chest', 'Compound'],
  },
  {
    id: 'chest-press-machine',
    name: 'Chest Press Machine',
    muscle: 'Chest',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Hammer Strength', 'Cable Crossover', 'Pec Deck'],
    tips: ['Keep shoulders down and back', 'Full stretch at bottom, squeeze at top', 'Avoid locking elbows harshly'],
    splitIds: ['ct', 'ctbb'],
    category: ['Chest', 'Compound'],
  },
  {
    id: 'incline-press',
    name: 'Incline Press',
    muscle: 'Chest',
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    variations: ['Incline Dumbbell', 'Incline Cable Fly', 'Landmine Press'],
    tips: ['Set bench to 30-45 degrees', 'Press in slight arc, not straight up', 'Keep wrists stacked over elbows'],
    splitIds: ['ct', 'ctbb'],
    category: ['Chest', 'Compound'],
  },
  {
    id: 'chest-fly',
    name: 'Chest Fly',
    muscle: 'Chest',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Cable Fly Mid', 'Pec Deck', 'Dumbbell Fly', 'High-to-Low Cable'],
    tips: ['Slight bend in elbows throughout', 'Feel stretch at bottom, squeeze at top', 'Control the negative'],
    splitIds: ['ct', 'ctbb'],
    category: ['Chest', 'Isolation'],
  },
  {
    id: 'push-ups',
    name: 'Push-ups',
    muscle: 'Chest',
    secondary: 'Triceps',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Standard', 'Wide Grip', 'Diamond', 'Archer'],
    tips: ['Brace core, straight body line', 'Lower chest to floor', 'Full lockout at top'],
    splitIds: ['ct', 'ctbb'],
    category: ['Chest', 'Compound'],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    muscle: 'Triceps',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Cable Rope', 'Cable Straight Bar', 'Single Arm Cable'],
    tips: ['Keep elbows pinned to sides', 'Extend fully without shoulder drift', 'Control the return'],
    splitIds: ['ct', 'ctbb'],
    category: ['Triceps', 'Isolation'],
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    muscle: 'Triceps',
    equipment: 'EZ Bar',
    difficulty: 'Intermediate',
    variations: ['EZ Bar', 'Dumbbell', 'Cable Overhead Extension'],
    tips: ['Lower bar toward forehead, not face', 'Keep upper arms stationary', 'Use moderate weight for elbow health'],
    splitIds: ['ct', 'ctbb'],
    category: ['Triceps', 'Isolation'],
  },
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    muscle: 'Triceps',
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    variations: ['Bodyweight', 'Weighted', 'Bench Dips', 'Machine Dips'],
    tips: ['Lean slightly forward for chest, upright for triceps', 'Lower until 90° elbow bend', 'Avoid shoulder shrug at bottom'],
    splitIds: ['ct', 'ctbb'],
    category: ['Triceps', 'Compound'],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    muscle: 'Triceps',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Dumbbell', 'Cable', 'EZ Bar'],
    tips: ['Keep elbows close to head', 'Full stretch overhead', 'Extend without arching lower back'],
    splitIds: ['ct', 'ctbb'],
    category: ['Triceps', 'Isolation'],
  },

  // BACK + BICEPS
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscle: 'Back',
    secondary: 'Legs',
    equipment: 'Barbell',
    difficulty: 'Advanced',
    variations: ['Conventional', 'Sumo', 'Romanian', 'Stiff Leg', 'Trap Bar'],
    tips: ['Hinge at hips, neutral spine', 'Bar close to shins', 'Drive through floor, lock hips at top'],
    splitIds: ['bb', 'ctbb', 'legs'],
    category: ['Back', 'Compound'],
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    muscle: 'Back',
    secondary: 'Biceps',
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    variations: ['Wide Grip', 'Neutral Grip', 'Close Grip', 'Assisted', 'Weighted'],
    tips: ['Initiate with lats, not arms', 'Full dead hang at bottom', 'Chin over bar at top'],
    splitIds: ['bb', 'ctbb'],
    category: ['Back', 'Compound'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    muscle: 'Back',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Wide Grip Bar', 'Close Grip', 'Single Arm', 'Reverse Grip'],
    tips: ['Pull bar to upper chest', 'Lean back slightly, chest up', 'Squeeze lats at bottom'],
    splitIds: ['bb', 'ctbb'],
    category: ['Back', 'Compound'],
  },
  {
    id: 'rows',
    name: 'Rows',
    muscle: 'Back',
    secondary: 'Biceps',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell Row', 'Seated Cable Row', 'T-Bar Row', 'Dumbbell Row', 'Chest-Supported Row', 'Pendlay Row'],
    tips: ['Pull elbows back, not up', 'Squeeze shoulder blades together', 'Keep torso stable'],
    splitIds: ['bb', 'ctbb'],
    category: ['Back', 'Compound'],
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight Arm Pulldown',
    muscle: 'Back',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Cable Rope', 'Cable Bar', 'Band'],
    tips: ['Arms stay straight with slight bend', 'Pull from lats, not triceps', 'Control the eccentric'],
    splitIds: ['bb', 'ctbb'],
    category: ['Back', 'Isolation'],
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    muscle: 'Shoulders',
    secondary: 'Back',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Cable Rope', 'Band'],
    tips: ['Pull to face level, externally rotate', 'Squeeze rear delts and rhomboids', 'Use lighter weight, higher reps'],
    splitIds: ['bb', 'ctbb', 'sh'],
    category: ['Back', 'Isolation'],
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    muscle: 'Biceps',
    equipment: 'Barbell',
    difficulty: 'Beginner',
    variations: ['Straight Bar', 'EZ Bar', 'Reverse Curl', '21s'],
    tips: ['Keep elbows at sides', 'No swinging or hip thrust', 'Full extension and contraction'],
    splitIds: ['bb', 'ctbb'],
    category: ['Biceps', 'Isolation'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    muscle: 'Biceps',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Dumbbell', 'Cable Rope', 'Cross-Body'],
    tips: ['Neutral grip throughout', 'Alternate or simultaneous both work', 'Control the negative'],
    splitIds: ['bb', 'ctbb'],
    category: ['Biceps', 'Isolation'],
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    muscle: 'Biceps',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Dumbbell', 'Cable', 'Preacher Curl Machine'],
    tips: ['Elbow braced on inner thigh', 'Curl without shoulder movement', 'Peak contraction at top'],
    splitIds: ['bb', 'ctbb'],
    category: ['Biceps', 'Isolation'],
  },
  {
    id: 'spider-curl',
    name: 'Spider Curl',
    muscle: 'Biceps',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell', 'Dumbbell', 'Cable'],
    tips: ['Chest against incline bench pad', 'Arms hang straight down', 'Curl without moving upper arm'],
    splitIds: ['bb', 'ctbb'],
    category: ['Biceps', 'Isolation'],
  },

  // SHOULDERS
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    muscle: 'Shoulders',
    secondary: 'Triceps',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell OHP', 'Dumbbell OHP', 'Arnold Press', 'Smith Machine', 'Machine Shoulder Press'],
    tips: ['Brace core, squeeze glutes', 'Bar path slightly back over head', 'Lock out without hyperextending'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Compound'],
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    muscle: 'Shoulders',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Dumbbell', 'Cable', 'Machine', 'Band'],
    tips: ['Lead with elbows, not hands', 'Raise to shoulder height', 'Slight forward lean helps'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Isolation'],
  },
  {
    id: 'front-raises',
    name: 'Front Raises',
    muscle: 'Shoulders',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Dumbbell', 'Barbell', 'Plate', 'Cable'],
    tips: ['Raise to eye level', 'Alternate arms or together', 'Avoid using momentum'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Isolation'],
  },
  {
    id: 'rear-delt',
    name: 'Rear Delt',
    muscle: 'Shoulders',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Reverse Pec Deck', 'Bent Over Fly', 'Face Pulls', 'Cable Rear Delt Fly'],
    tips: ['Focus on rear delt, not traps', 'Bent over: torso parallel to floor', 'Squeeze at top of each rep'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Isolation'],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    muscle: 'Shoulders',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell', 'Dumbbell', 'Cable', 'EZ Bar'],
    tips: ['Pull elbows higher than wrists', 'Stop at chest level to protect shoulders', 'Use moderate grip width'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Compound'],
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    muscle: 'Shoulders',
    equipment: 'Barbell',
    difficulty: 'Beginner',
    variations: ['Barbell', 'Dumbbell', 'Smith Machine', 'Cable'],
    tips: ['Shrug straight up, not roll', 'Hold peak contraction briefly', 'Keep arms straight'],
    splitIds: ['sh'],
    category: ['Shoulders', 'Isolation'],
  },
  {
    id: 'landmine-press',
    name: 'Landmine Press',
    muscle: 'Shoulders',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Single Arm', 'Both Arms'],
    tips: ['Press on arc path', 'Brace core against rotation', 'Full extension at top'],
    splitIds: ['sh', 'ct'],
    category: ['Shoulders', 'Compound'],
  },

  // LEGS
  {
    id: 'squat',
    name: 'Squat',
    muscle: 'Legs',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell Back Squat', 'Front Squat', 'Goblet Squat', 'Hack Squat', 'Leg Press', 'Smith Machine Squat'],
    tips: ['Break at hips and knees together', 'Knees track over toes', 'Depth: hip crease below knee'],
    splitIds: ['legs'],
    category: ['Legs', 'Compound'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    muscle: 'Legs',
    secondary: 'Back',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell RDL', 'Dumbbell RDL', 'Single Leg RDL', 'Cable RDL'],
    tips: ['Hinge at hips, slight knee bend', 'Bar stays close to legs', 'Feel hamstring stretch at bottom'],
    splitIds: ['legs'],
    category: ['Legs', 'Compound'],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    muscle: 'Legs',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Seated Leg Curl', 'Lying Leg Curl', 'Nordic Curl', 'Standing Leg Curl'],
    tips: ['Curl without lifting hips', 'Full contraction at top', 'Slow eccentric for hamstring growth'],
    splitIds: ['legs'],
    category: ['Legs', 'Isolation'],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    muscle: 'Legs',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Machine', 'Single Leg', 'Band'],
    tips: ['Align knee with machine pivot', 'Squeeze quads at top', 'Control the lowering phase'],
    splitIds: ['legs'],
    category: ['Legs', 'Isolation'],
  },
  {
    id: 'lunges',
    name: 'Lunges',
    muscle: 'Legs',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    variations: ['Walking Lunges', 'Reverse Lunges', 'Bulgarian Split Squat', 'Lateral Lunge', 'Deficit Lunge'],
    tips: ['Front knee over ankle, not past toes', 'Torso upright', 'Drive through front heel'],
    splitIds: ['legs'],
    category: ['Legs', 'Compound'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    muscle: 'Legs',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    variations: ['Barbell', 'Dumbbell', 'Machine', 'Band'],
    tips: ['Chin tucked, ribs down', 'Drive hips up, squeeze glutes', 'Pause at top'],
    splitIds: ['legs'],
    category: ['Legs', 'Compound'],
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    muscle: 'Legs',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Standing Calf Raise', 'Seated Calf Raise', 'Leg Press Calves', 'Donkey Calf Raise'],
    tips: ['Full stretch at bottom', 'Pause at top contraction', 'Control tempo, avoid bouncing'],
    splitIds: ['legs'],
    category: ['Legs', 'Isolation'],
  },
  {
    id: 'abductors-adductors',
    name: 'Abductors/Adductors',
    muscle: 'Legs',
    equipment: 'Machine',
    difficulty: 'Beginner',
    variations: ['Hip Abductor Machine', 'Hip Adductor Machine', 'Cable Hip Abduction', 'Band Walk'],
    tips: ['Sit upright in machine', 'Controlled reps, no slamming weight', 'Squeeze at end range'],
    splitIds: ['legs'],
    category: ['Legs', 'Isolation'],
  },

  // CORE
  {
    id: 'plank',
    name: 'Plank',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Standard', 'Forearm Plank', 'Side Plank', 'RKC Plank', 'Weighted'],
    tips: ['Brace abs and glutes', 'Neutral spine, no sagging hips', 'Breathe steadily throughout hold'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Compound'],
  },
  {
    id: 'crunches',
    name: 'Crunches',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Standard', 'Cable Crunch', 'Machine Crunch', 'Decline Crunch', 'Bicycle Crunch'],
    tips: ['Curl ribs toward pelvis, not neck', 'Exhale on the crunch', 'Control the negative'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Isolation'],
  },
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    variations: ['Straight Leg', 'Bent Knee', 'Toes to Bar', "Captain's Chair"],
    tips: ['Minimize swinging', 'Posterior pelvic tilt at top', 'Lower with control'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Compound'],
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Bodyweight', 'Dumbbell', 'Medicine Ball', 'Cable', 'Weighted'],
    tips: ['Rotate from torso, not arms', 'Feet elevated for more challenge', 'Keep chest up'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Isolation'],
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    muscle: 'Core',
    equipment: 'Ab Wheel',
    difficulty: 'Advanced',
    variations: ['Kneeling', 'Standing', 'Barbell Rollout', 'Band Assisted'],
    tips: ['Brace hard before rolling out', 'Stop before lower back arches', 'Pull back with abs, not hips'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Compound'],
  },
  {
    id: 'cable-woodchoppers',
    name: 'Cable Woodchoppers',
    muscle: 'Core',
    equipment: 'Cable',
    difficulty: 'Intermediate',
    variations: ['High to Low', 'Low to High', 'Standing', 'Kneeling'],
    tips: ['Pivot feet and rotate hips', 'Arms stay extended', 'Control both directions'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Compound'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Standard', 'Weighted', 'Band Resisted', 'Alternating'],
    tips: ['Press lower back into floor', 'Move opposite arm and leg slowly', 'Exhale as limbs extend'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Isolation'],
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    muscle: 'Core',
    secondary: 'Shoulders',
    equipment: 'Cable',
    difficulty: 'Beginner',
    variations: ['Cable', 'Band', 'Half-Kneeling', 'Standing'],
    tips: ['Resist rotation — stay square', 'Press straight out from chest', 'Brace core throughout'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Compound'],
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    variations: ['Standard', 'Weighted', 'Hollow Rocks', 'Tuck Hold'],
    tips: ['Lower back pressed to floor', 'Arms and legs extended', 'Hold without losing position'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Isolation'],
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    muscle: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    variations: ['Lying Leg Raise', 'Decline', "Captain's Chair", 'Flutter Kicks'],
    tips: ['Posterior pelvic tilt at top', 'Avoid momentum from hips', 'Lower legs without arching back'],
    splitIds: ['core', 'coresh'],
    category: ['Core', 'Isolation'],
  },
];

export function getExercisesForSplit(splitId: string): LibraryExercise[] {
  if (splitId === 'ctbb') {
    return EXERCISE_LIBRARY.filter((e) => e.splitIds.includes('ct') || e.splitIds.includes('bb'));
  }
  if (splitId === 'coresh') {
    return EXERCISE_LIBRARY.filter(
      (e) => e.splitIds.includes('core') || e.splitIds.includes('sh')
    );
  }
  return EXERCISE_LIBRARY.filter((e) => e.splitIds.includes(splitId as 'ct'));
}

export function getExerciseById(id: string): LibraryExercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}
